---
label: product
hide_body: true
fields:
- type: text
  name: name
  label: name
- type: file
  name: image
  label: image
- type: file
  name: image2
  label: image2
- type: text
  name: image3
  label: image3
- type: text
  name: image4
  label: image4
- type: file
  name: cartImage
  label: cartImage
- type: text
  name: shortDescription
  label: shortDescription
- type: number
  name: price
  label: price
- type: text
  name: id
  label: id
- type: text
  name: url
  label: url
